tfa.settings:
  type: mapping
  label: 'TFA settings'
  mapping:
    enabled:
      type: integer
      label: 'TFA enabled'
    setup_plugins:
      type: sequence
      label: 'TFA plugins'
    send_plugins:
      type: sequence
      label: 'Send plugins'
    login_plugins:
      type: sequence
      label: 'Login plugins'
    validate_plugin:
      type: string
      label: 'Current validation plugin'
    fallback_plugins:
      type: sequence
      label: 'Fallback plugins'
