tfa.settings:
  type: mapping
  label: 'TFA settings'
  mapping:
    secret_key:
     type: string
     label: 'Secret key to to use as encryption key for TOTP seed encryption. Should be set in settings.php and not in the Drupal database.'
    time_skew:
     type: integer
     label: 'Number of 30 second chunks to allow TOTP keys between.'
    recovery_codes_amount:
     type: integer
     label: 'Recovery codes amount. Default is 10.'
    enabled:
      type: integer
      label: 'TFA enabled'
    setup_plugins:
      type: sequence
      label: 'TFA plugins'
    send_plugins:
      type: sequence
      label: 'Send plugins'
    login_plugins:
      type: sequence
      label: 'Login plugins'
    validate_plugin:
      type: string
      label: 'Current validation plugin'
    fallback_plugins:
      type: sequence
      label: 'Fallback plugins'
    help_text:
      type: string
      label: 'Text to display on help page. Plain text only.'

